Repository microsoft/azure-devops-mcp, pull requests merged in 2025-08, with the labels that each got.

#270 Add Advanced Security Alert tools
  README.md
  src/tools.ts
  src/tools/advsec.ts
  src/utils.ts
  test/src/tools/advsec.test.ts
  test/src/utils.test.ts
Labels: Needs Review 👓, Waiting for Author 🔨, Stale and Needs Attention ✈️

#385 Added optional fields param to get work items in batch
  src/tools/workitems.ts
  test/src/tools/workitems.test.ts
Labels: Waiting for Merge 🚘

#423 docs: enhance examples for adding artifact links to work items
  docs/EXAMPLES.md
Labels: Documentation 📙, Waiting for Merge 🚘

#391 Explicit instructions for expected result format
  src/tools/testplans.ts
  test/src/tools/testplan.test.ts
Labels: Needs Review 👓, Test Plans 🧪

#374 [feat]: Add wiki creation and update functionality
  README.md
  src/tools/wiki.ts
  test/src/tools/wiki.test.ts
Labels: Do Not Merge ❌, Wiki 📄, Waiting for Author 🔨

#433 Series of misc changes
  README.md
  docs/EXAMPLES.md
  src/prompts.ts
  src/tools/wiki.ts
  test/src/tools/wiki.test.ts
Labels: Needs Review 👓, Waiting for Merge 🚘
