Repository microsoft/azure-devops-mcp, pull requests merged in 2025-07, with the labels that each got.

#153 feat: add initial prompts for experimentation
  src/prompts.ts
Labels: Needs Review 👓

#164 Update date handling in configuration functions to use z.coerce.date()
  src/tools/builds.ts
  src/tools/releases.ts
  src/tools/workitems.ts
Labels: Needs Review 👓

#223 Fixing bug with update_pull_request_status (Issue #184)
  src/tools/repos.ts
Labels: Approved ✅

#261 updated create_work_item to support markdown format in large text fields
  docs/HOWTO.md
  src/tools/workitems.ts
  test/src/tools/workitems.test.ts
Labels: Needs Review 👓

#284 fix: to link work items to pr
  src/tools/workitems.ts
  test/src/tools/workitems.test.ts
Labels: Waiting for Merge 🚘

#294 docs: Update to include Claude Code instructions
  docs/HOWTO.md
Labels: Documentation 📙, Needs Review 👓

#297 Support for affects and affected by for adding work item links
  src/tools/workitems.ts
  test/src/tools/workitems.test.ts
Labels: Needs Review 👓, Waiting for Merge 🚘

#260 feat: add create pull request thread tool
  README.md
  src/tools/repos.ts
Labels: Waiting for Author 🔨

#326 Fixing issue with casing on operations `wit_update_work_item` rejects…
  src/tools/workitems.ts
  test/src/tools/workitems.test.ts
Labels: Waiting for Merge 🚘

#351 Added `includeWorkItemRefs` param to the `repo_get_pull_request_by_id` tool
  src/tools/repos.ts
Labels: Needs Review 👓

#363 AssignedTo transformation for get work items in batch
  src/tools/workitems.ts
  test/src/tools/workitems.test.ts
Labels: Waiting for Merge 🚘

#365 Adding work_item_unlink to remove links from a work item
  README.md
  docs/EXAMPLES.md
  src/tools/workitems.ts
  test/src/tools/workitems.test.ts
Labels: Waiting for Merge 🚘

#361 Add pull request update tool
  README.md
  src/tools/repos.ts
  test/src/tools/repos.test.ts
Labels: Needs Review 👓, Repos 📁
